#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -It 3 ]; then
        echo "Usaage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -It 4 ]; then
        scp -0 StrictHostKeyChecking=no "$1" "$3@$2":;~/
else
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
