#!/usr/bin/env bash
# bash script that configures a server to the connect to a port

apt-get update
apt-get install -y nginx
sed -i 's/\(listen\s* \[::\]:\)\?80;/g' /etc/nginx/sites-available/default
service nginx restart
