#!/usr/bin/env bash
# shorter bash script

apt-get update
apt-get install -y nginx
sed -i 's/\(listen\s* \[::\]:\)\?80;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
netstart -tuplin | grep ':80' > /dev/null 2>&1 || echo "Nginx is not running"
