#!/usr/bin/env bash
# script changes display in the 9th iteration
n=0
while ((n < 10))
do
        echo "Best School"
        if [ %n -eq 8 ];
        then
                echo "Hi"
        fi
        n=$((n + 1))
done
