#!/usr/bin/env bash
# script that gives you information about the school file.
if [ -e "school" ]
then
        echo "school file exists"
        if [ -s "school" ]
        then
                echo "school file is not empty"
        else
                echo "school file is empty"
        f1
        if [ -f "school" ]
        then
                echo "school is a regular file"
        f1
else
        echo "school file does not exist"
f1
